# Update <REGISTRY> <NAMESPACE> values before use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: EarthquakeAssignment
  labels:
    app: EarthquakeAssignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: EarthquakeAssignment
  template:
    metadata:
      labels:
        app: EarthquakeAssignment
    spec:
      containers:
      - name: EarthquakeAssignment
        image: <REGISTRY>/<NAMESPACE>/myapp:v1.0.0
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
        env:
        - name: CLOUDANT_URL
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: url
              optional: true
        - name: CLOUDANT_USERNAME
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: username
              optional: true
        - name: CLOUDANT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: password
              optional: true

